### PR TITLE
Nix flake

### PR DESCRIPTION
**Pull request by mjakobsche**
Hey,
I created this flake, which allows users to install ki-editor using nix. It also defines an environment with basic packages for development . If there is something I should add or fix, let me know. 
I think it will encourage more people to contribute ;> and make the installation process even more simple.

### CODE REVIEW

**Comment by wongjiahau** [comment]
I’m going to trust you on this one as I’m not well-versed in Nix.

Thanks for the contribution @mjakobsche!

**Comment by evelant** [comment]
Unfortunately this does not compile for me on mac (aarch64-darwin). It fails with a linker error building libz-sys `note: ld: library not found for -liconv`. A missing dep?

**Comment by mjakobsche** [comment]
You are correct. I will fix it.

**Comment by mjakobsche** [comment]
@evelant could you let me know if this fixes the issue:
`buildInputs = with pkgs; [
            openssl
          ] ++ lib.optionals pkgs.stdenv.isDarwin [
            libiconv
            curl
            darwin.apple_sdk.frameworks.AppKit
          ]; `

**Pull request merged**
