### PR TITLE
feat(cli): make edit the default command

### PR DESCRIPTION
**Pull request by jcowgar**
See #484.

This PR hides the "edit" command and makes it default.

Examples are given at the root of the ki-language git repo.

* `ki` -- opens [ROOT] window as it always has
* `ki readme.md` -- opens `readme.md`
* `ki src` -- opens the File Explorer for the `src` directory
* `ki log` -- opens a new file named `log`
* `ki @ log` -- prints log path and exits
* `ki @ grammar` -- shows grammar help and exits
* `ki @ grammar build` -- builds grammar and exits

New help output from `ki --help`:

```
Usage: ki [PATH] [COMMAND]

Commands:
  @     Run commands
  help  Print this message or the help of the given subcommand(s)

Arguments:
  [PATH]

Options:
  -h, --help     Print help
  -V, --version  Print version
```

Output of `ki @ --help`

```
Run commands

Usage: ki @ <COMMAND>

Commands:
  grammar          Build and fetch tree-sitter grammar files
  highlight-query  Manage cached tree-sitter highlight files
  log              Prints the log file path
  in               Run Ki in the given path, treating the path as the working directory
  help             Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

### CODE REVIEW

**Comment by lydell** [comment]
If I have a folder called “log” or “grammar”, is it possible to open the File Explorer for either of those folders? Is it `ki ./log` and `ki ./grammar` maybe?

**Comment by jcowgar** [comment]
> If I have a folder called “log” or “grammar”, is it possible to open the File Explorer for either of those folders? Is it `ki ./log` and `ki ./grammar` maybe?

That is exactly how it will work with this PR.

You can, however, do it right now, prior to this PR, by `ki edit ./grammar` or `ki edit ./log`.

**Comment by jcowgar** [comment]
I just thought of a conflict here, maybe it is what @wongjiahau was thinking of to begin with but say you have a directory named `log`, and you type `ki log`. It would execute the `log` command printing the path to the log file. It wouldn't open the `log` directory like `ki src` would.

This will happen with grammar, highlight-query, log, in and help.

I think this is an acceptable state to make using ki much easier. I think that the number of times you will try to edit a directory named log, grammar, highlight-query or help will be minimal.

You can work around this by prefixing your file path with a `./`, i.e. `ki ./log` will open the log directory in ki just fine, not launch the log command.

**Comment by wongjiahau** [comment]
I actually name a log file as `log` quite a lot, but regardless I think the subcommands need to be nested for the consistency and predictability, otherwise it will become like `npm` where you are never sure what xxx is in `npm xxx`, as it could be either a built-in command or user-defined comnand.

**Comment by jcowgar** [comment]
> I actually name log files as `log` quite a lot, but regardless I think the subcommands need to be nested for the consistency and predictability, otherwise it will become like `npm` where you are never sure what xxx is in `npm xxx`, as it could be either a built-in command or user-defined comnand.

I'm not sure what this means. Can you give me an example what you mean about subcommands being nested?

**Comment by wongjiahau** [comment]
Yea sure, for example:

```
ki --run log
ki --run grammar fetch
```

**Comment by jcowgar** [comment]
I understand now. I'll make the necessary changes.

**Comment by wongjiahau** [comment]
I've decided to take compromises by nesting the existing subcommands under the `@` subcommand, this offers the best of both worlds:
1. It allows `ki <filename>` to work
2. Its implementation is not unconventional

The only drawback is that if a user ever wants to open a file named `@`, he has to do `ki ./@`, sort of like escaping backslash in a string literal.

**Review by wongjiahau — APPROVED** [review]

**Pull request merged**
