### PR TITLE
feat(lsp): zig

### LINKED ISSUE #314: feat(lsp): zig
Add lsp configuration for zig.

### PR DESCRIPTION
**Pull request by yves-biener**
closes #314

### CODE REVIEW

**Comment by yves-biener** [comment]
there is currently one issue, that the formatting is not working as expected, as the format command requires the file path as an argument. How can I provide that parameter accordingly?

**Comment by wongjiahau** [comment]
Variable substitution is not currently supported yet, but on the other hand, it seems like you can add the `--stdin` flag after `zig fmt` to make it work.

Reference: 
https://github.com/ziglang/zig/blob/d6d09f4ea7cc590035bf8af6617f93767423c691/lib/compiler/fmt.zig#L19

**Comment by yves-biener** [comment]
You are right, thank you for the hint. I added the argument and tested it successfully 🎉

**Comment by wongjiahau** [comment]
Thanks for your contribution!

**Pull request merged**
