### PR TITLE
"ki edit ." now opens file explorer instead of crashing.

### PR DESCRIPTION
**Pull request by AlphabetsAlphabets**
It used to crash at `main.rs` where `cli::cli.unwrap()` was called because you'd just get an `Err` as the `edit` match arm wasn't able to handle a directory instead of a file. The file explorer does open but it is slow. I'm wondering if it's an issue of how I opened the file explorer or if it's an issue of the file explorer.

There is a bug where `ki edit ..` opens the current directory instead of the parent directory (will work on it) but I thought to just open the PR so it is kept track of it.

### CODE REVIEW

**Comment by wongjiahau** [comment]
Thanks @AlphabetsAlphabets! Can you fix the Github actions error by using `rustfmt 1.7.0-stable (05147895 2024-07-21)`?

**Comment by AlphabetsAlphabets** [comment]
Yes, I can do that. But I'm still worried about the performance of the File Explorer. It's a bit slow, and I'm not sure if my way of invoking it is the right way. Unless the explorer is just slower which I don't think it is.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by wongjiahau** [comment]
I don't think your code is causing the performance issue, but if I were pedantic, the file explorer should be opened in the directory passed from the CLI arguments.

**Comment by AlphabetsAlphabets** [comment]
@wongjiahau I've done the formatting with rustfmt, feel free to push. But the bug of opening the current dir when `ki edit ..` is still there. 

I'm trying my best to fix it but I'm a little confused and would like some help. I'll save the yapping lol but basically, I'd like to know your debugging setup. If you think it's better to open a discussion, I'll do just that. I'm also in the matrix chat if you prefer that I DM you there, either way is fine.

**Comment by wongjiahau** [comment]
Yea sure! Let’s discuss on Matrix, can you DM me?

**Comment by AlphabetsAlphabets** [comment]
Thanks :) I'll send my question over. I won't be able to respond immediately though just FYi

Sent from Proton Mail Android

-------- Original Message --------

**Comment by AlphabetsAlphabets** [comment]
@wongjiahau hi, I managed to fix the bug with "ki edit .." opens the cwd instead of parent.

**Pull request merged**
